### ISSUE TITLE
Should add this Varnish module to the VMOD listing

### ISSUE THREAD

**Issue by huayra** [nand2/libvmod-throttle#1]
Hi,

Just wanted to give you a heads up about adding this module to the VMOD listing in the Varnish cache community site:
 https://www.varnish-cache.org/vmods

Making a user on the site should be fairly simple to do and from there you can manage your VMODs and post to the forum, etc...

Best, Rubén.

**Comment by nand2** [comment]
Thanks for the heads up!
I was actually planning to do that when finished, but I see I can in fact put it here and mark it "in development".
I have added it, now awaiting moderator acceptation.

Current plan is to finish it in the next 2 weeks, and to start testing for a live deploy.

Cheers,
Nicolas
