### ISSUE TITLE
Ubuntu Package

### ISSUE THREAD

**Issue by gschoenberger** [nand2/libvmod-throttle#15]
Hi!

Any documentation on how to build a package from the "debian" files?

THX, Georg

**Comment by nand2** [comment]
Hello!

To be honest, I have no idea :)
The only pointer I can give you is that this module, and the debian files in it, comes from libvmod-example at https://github.com/varnish/libvmod-example

Good luck!

**Comment by gschoenberger** [comment]
OK THX, I will try my best!
