### ISSUE TITLE
Function to retrieve remaining requests

### ISSUE THREAD

**Issue by syphernl** [nand2/libvmod-throttle#2]
It would be nice if there was a function that returns the amount of requests for the given timeframe, so this can be added to a response header for easy implementation.

**Comment by nand2** [comment]
Good idea. I'll add that this WE.

**Comment by syphernl** [comment]
Thanks! Loving this vmod btw, I'm using it to ratelimit my API.

**Comment by nand2** [comment]
Great! You're then my first production user :)
Tell me if you have issues.

**Comment by nand2** [comment]
Ok it's available.
