### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by syphernl** [nand2/libvmod-throttle#5]
It would be awesome if Redis could be used to store the data. 
This would make it possible to running multiple Varnish instances (on multiple servers) which share the same values, otherwise it would mean that every node has their own limits.

Redis has atomic increments, so that should be safe to use.

**Comment by nand2** [comment]
That would indeed be awesome!
Unfortunately I don't have the time to work on this ATM, but any contributions are welcome -- as long as both with-redis and without-redis modes work independently :)
