### ISSUE TITLE
release ?

### ISSUE THREAD

**Issue by kapouer** [nand2/libvmod-throttle#9]
hi,
it'd be nice to give a version and tag this software !

**Comment by huayra** [comment]
On that note:

If you have ideas on how to tag this and other VMODs in general, please let
me know.

Varnish 4 will have VMODs for everything and I think we should have a
better way of keeping track of VMODs and their versions than we currently
have on http://varnish.org/vmods

## Best,

Rubén Romero
Varnish Software
Den 12. des. 2013 17.56 skrev "Jérémy Lal" notifications@github.com
følgende:

**Comment by kapouer** [comment]
I realize there's a bigger picture now :)
"internal" vmods will probably be versioned after current varnish release,
and "external" ones would have their own versions and requirements of which varnish version
they're compatible with.
I don't think you can really encode all that information in a version number, but making a
(somehow arbitrary) distinction between internal (or supported) plugins and external (or unsupported)
would help users understand what's part of the varnish release and what's not.
Hope this helps...

**Comment by nand2** [comment]
Good question!

I choose to tag it 'v3-1.0', which says version 1.0 for varnish 3. But I'll use a global versioning scheme for external vmods once it's decided.
